version: 2

jobs:
  build:
    docker:
      - image: scoodah/yadc:build
    working_directory: /go/src/github.com/mikhailswift/yadc
    steps:
      - checkout
      - run:
          name: Dependencies
          command: make dep
      - run:
          name: Build
          command: make build
  test:
    docker:
      - image: scoodah/yadc:build
    working_directory: /go/src/github.com/mikhailswift/yadc
    steps:
      - checkout
      - run:
          name: Dependencies
          command: make dep
      - run:
          name: Test
          command: |
            make test
            bash <(curl -s https://codecov.io/bash)
  code_quality:
    docker:
      - image: scoodah/yadc:build
    working_directory: /go/src/github.com/mikhailswift/yadc
    steps:
      - checkout
      - run:
          name: Code Quality Checks
          command: |
            make fmt
            make vet
            make lint

workflows:
  version: 2
  yacd:
    jobs:
      - build
      - test
      - code_quality
